  #Sudo Group Setup
  #From: https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml#L14
  - name: Make sure we have a 'wheel' + other groups
    group:
      name: "{{item.group}}"
      state: present
    with_items: "{{createUser}}"

  # - name: debug group permissions
  #   debug: 
  #     msg: item group is = {{item.group}}
  #   with_items: "{{groupPermissions}}"  

  - name: Set group permissions
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%{{item.group}}'
      line: "{{item.permission}}"
      validate: '/usr/sbin/visudo -cf %s'
    become: true
    with_items: "{{groupPermissions}}"

  # User + Key Setup
  #From: https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml#L14
  - name: Create new user with specified privileges
    user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.group }}"
      append: true
      create_home: true
      shell: /bin/bash
    with_items: "{{createUser}}"
    become: true

  - name: Set authorized key for remote user
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.copy_local_key }}"
    with_items: "{{createUser}}"
    become: true

  - name: Disable password authentication for root
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'
    become: true

