  #Sudo Group Setup
  #From: https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml#L14
  - name: Make sure we have a 'wheel' + other groups
    group:
      name: "{{item.group}}"
      state: present
    with_items: "{{createUser}}"
  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD:ALL'
      validate: '/usr/sbin/visudo -cf %s'
    become: true

  # User + Key Setup
  #From: https://github.com/do-community/ansible-playbooks/blob/master/setup_ubuntu1804/playbook.yml#L14
  - name: Create a new regular user with sudo privileges
    user:
      name: "{{ item.name }}"
      state: present
      groups: wheel
      append: true
      create_home: true
      shell: /bin/bash
    with_items: "{{createUser}}"
    when: item.group == "wheel"
    become: true

  - name: Set authorized key for remote user
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.copy_local_key }}"
    with_items: "{{createUser}}"
    become: true

  - name: Disable password authentication for root
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'
    become: true

