version: "3.7"
services:
  plex:
    image: linuxserver/plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      # - PLEX_CLAIM=
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage/TV Shows:/tv
      - /mnt/storage/Movies:/movies
      - /mnt/storage/Music:/Music
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
      - target: 32400
        published: 32400
        protocol: udp
        mode: host   
      - target: 32469 
        published: 32469
        protocol: tcp
        mode: host        
      - target: 32469 
        published: 32469
        protocol: udp
        mode: host 
      - target: 5353
        published: 5353
        protocol: udp
        mode: host 
      - target: 1900
        published: 1900
        protocol: udp
        mode: host 