snapraid_apt_package_name: snapraid
snapraid_bin_path: /usr/local/bin/snapraid

snapraid_healthcheck_io_uuid: ""

snapraid_email_address: ""
snapraid_TO_email_address: ""
snapraid_gmail_pass: ""

snapraid_config_excludes:
  - "*.unrecoverable"
  - "/tmp/"
  - "/lost+found/"
  - "downloads/"
  - "appdata/"
  - "snapshots/"
  - "*.!sync"
  - ".AppleDouble"
  - "._AppleDouble"
  - ".DS_Store"
  - "._.DS_Store"
  - ".Thumbs.db"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - ".AppleDB"
snapraid_config_hidden_files_enabled: true
snapraid_config_hidden_files: nohidden
snapraid_config_path: /etc/snapraid.conf

snapraid_run_path: /opt/snapraid-runner/snapraid-runner
snapraid_run_conf: "{{ snapraid_run_path }}.conf"
snapraid_run_bin: "{{ snapraid_run_path }}.py"
snapraid_run_command: "python3.8 {{ snapraid_run_bin }} -c {{ snapraid_run_conf}} && curl -fsS --retry 3 https://hc-ping.com/{{ snapraid_healthcheck_io_uuid }} > /dev/null"
snapraid_run_scrub: true
snapraid_run_scrub_percent: 22
snapraid_run_scrub_age: 8
snapraid_touch: true

snapraid_cron_jobs:
  - { job: '{{ snapraid_run_command }}', name: 'snapraid_runner', weekday: '*', hour: '01' }