#Create mount points
#Alternatively, do it manually using: sudo mkdir /path/to/mountpoint
- name: create /mnt points
  file: 
    path: "/mnt/{{item}}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0777
    #access_time: preserve
    #modification_time: now
  with_items: "{{mntpoints.name}}"
  
#Mount the disks
- name: mount disks
  mount:
    path: "/mnt/{{item.name}}"
    src: UUID="{{item.src}}"
    fstype: "{{item.type}}"
    state: mounted
  with_items: "{{mntpoints}}"
    
#Create and mount the mergerfs file system

