#Create mount points
#Alternatively, do it manually using: sudo mkdir /path/to/mountpoint
- name: create /mnt points
  file: 
    path: /mnt/{{item.name}}
    state: directory
    mode: 0777
  with_items: "{{mntpoints}}"
  become: true
  
# - name: debug mount points
#   debug: 
#     msg: mountpoint is = /mnt/{{item.name}}
#   with_items: "{{mntpoints}}"  

#Mount the disks
- name: mount disks
  mount:
    path: /mnt/{{item.name}}
    src: UUID={{item.UUID}}
    fstype: "{{item.type}}"
    # Need ansible 2.9 for remounted option, see: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu
    state: mounted
    opts: nodev,nosuid,noexec,noatime,nodiratime
  with_items: "{{mntpoints}}"
  become: true
    
#Create and mount the mergerfs file system



#   - { name: disk1, type: ext4, src: 37795d34-dd06-4592-9826-005de3ad2a45}
#   - { name: disk2, type: ext4, src: b9827244-f281-4efc-baba-70d50b8231bf}


# - name: mount mergerfs array
#   mount:
#     name: /mnt/storage
#     src: /mnt/disk*
#     opts: direct_io,defaults,allow_other,minfreespace=20G,fsname=mergerfs
#     fstype: fuse.mergerfs
#     # change to 'mounted' to auto mount
#     state: present
