#Create mount points
#Alternatively, do it manually using: sudo mkdir /path/to/mountpoint
- name: create /mnt points
  file: 
    path: /mnt/{{item.name}}
    state: directory
    mode: 0777
  with_items: "{{mntpoints}}"
  become: true
  
# - name: debug mount points
#   debug: 
#     msg: mountpoint is = /mnt/{{item.name}}
#   with_items: "{{mntpoints}}"  

#Mount the disks
#The mount  module always reports changed for some stupid reason.
- name: add fstab entry for disks
  mount:
    path: /mnt/{{item.name}}
    src: UUID={{item.UUID}}
    fstype: "{{item.type}}"
    # Need ansible 2.9 for remounted option, see: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu
    state: present
    opts: nodev,nosuid,noexec,noatime,nodiratime
  with_items: "{{mntpoints}}"
  become: true

- name: Install mergerfs package
  apt:
    pkg:
      - mergerfs
    state: present
  become: true     
    
#Create and mount the mergerfs file system
- name: add fstab entry for mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: defaults,allow_other,direct_io,use_ino,hard_remove,dropcacheonclose=true,fsname=mergerfs
    fstype: fuse.mergerfs
    state: present 
  become: true

- name: reload fstab
  # Needed to add this for mounts to appear properly, without rebooting
  # https://unix.stackexchange.com/questions/477794/how-to-force-os-reload-of-fstab
  systemd: 
    daemon_reload: yes
  become: true