#Create mount points
#Alternatively, do it manually using: sudo mkdir /path/to/mountpoint
- name: create /mnt points
  file: 
    path: /mnt/{{item.name}}
    state: directory
    mode: 0777
  with_items: "{{mntpoints}}"
  become: true
  
# - name: debug mount points
#   debug: 
#     msg: mountpoint is = /mnt/{{item.name}}
#   with_items: "{{mntpoints}}"  

#Mount the disks
#The mount  module always reports changed for some stupid reason.
- name: mount disks
  mount:
    path: /mnt/{{item.name}}
    src: UUID={{item.UUID}}
    fstype: "{{item.type}}"
    # Need ansible 2.9 for remounted option, see: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu
    state: mounted
    opts: nodev,nosuid,noexec,noatime,nodiratime
  with_items: "{{mntpoints}}"
  become: true
    
#Create and mount the mergerfs file system
- name: mount mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=20G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: present
