- name: docker swarm init
  docker_swarm:
    state: present
  become: true

- name: copy docker-compose.yml into position
  copy:
    src: "/mnt/c/Users/Tom-Erik/Google Drive/repos/homeAutomation/ansible/roles/docker-compose/deploy/docker-compose.yml"
    dest: "/opt/docker-compose.yml"
    owner: nobody
    group: nogroup
    mode: 0775
  become: true

- name: deploy stack from a compose file
  docker_stack:
    state: present
    name: "{{myStack}}"
    prune: yes
    compose:
      - "/opt/docker-compose.yml"
  become: true

- name: modify network to host networking
  docker_swarm_service:
    name: "{{myStack}}_plex"
    networks: host
  ignore_errors: yes
  register: out
- debug: var=out
- debug: 
    msg: "{{myStack}}_plex"

#Run to check which containers are running
# sudo docker node ps $(docker node ls -q)
# sudo docker node ps cartman

#To get long error messages:
# sudo docker service ps plexStack_plex --no-trunc