- name: bazarr container
  docker_container:
    name: bazarr
    image: linuxserver/bazarr
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timeZone }}"
      UMASK_SET: "022" #optional
    volumes:
      - "{{ appData }}/bazarr:/config"
      - "{{ storageData }}:{{ storageData }}"
      - "{{ storageData }}/empty:/movies"
      - "{{ storageData }}/empty:/tv"
    network_mode: host
    pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped
  become: true

- name: allow bazarr in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "6767"
  become: true