- name: "Home Assistant: Custom container - Circadian_lighting - Create dir"
  file:
    dest: "{{ appData }}/homeAssistant/custom_components/circadian_lighting/"
    state: directory
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
  become: true

- name: "Home Assistant: Custom container - Circadian_lighting - Fetch files"
  get_url:
    url: "https://raw.githubusercontent.com/claytonjn/hass-circadian_lighting/master/custom_components/circadian_lighting/{{ circadianFiles }}"
    dest: "{{ appData }}/homeAssistant/custom_components/circadian_lighting/"
    mode: 0644
    owner: dockeruser
    force: yes
  with_items:
    - "__init__.py"
    - "sensor.py"
    - "switch.py"
    - "manifest.json"
    - "services.yaml"
  loop_control:
    loop_var: circadianFiles
  become: true

- name: Install packages required by Home Assistant
  apt:
    pkg:
      - bluetooth # Req. by bluetooth-tracker
      - libbluetooth-dev # Req. by bluetooth-tracker
    state: present
  become: true

- name: Home Assistant container
  docker_container:
    name: homeAssistant
    image: homeassistant/home-assistant:stable
    env:
      TZ: "{{ timeZone}} "
    volumes:
      - "{{ appData }}/homeAssistant:/config"
    network_mode: host
    pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped
  become: true

- name: allow Home Assistant in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "8123"
  become: true

# - name: setup cron job snapraid-runner
#   cron:
#     user: "root"
#     job: "docker container restart homeAssistant"
#     name: "homeAssistant_restart"
#     weekday: "*"
#     minute: "00"
#     hour: "03"
#     dom: "*"
#   become: true

- name: Copy private key for remote user (ASUSWRT Integration)
  copy:
    src: "{{ sshFiles }}"
    dest: "{{ appData }}/homeAssistant/secrets/ssh/"
    mode: 0600
  with_items:
    - "/mnt/c/Users/Tom-Erik/.ssh/id_rsa_ansibleAdminHome"
    # - "{{ lookup('file','/mnt/c/Users/Tom-Erik/.ssh/id_rsa_ansibleAdminHome') }}"
  loop_control:
    loop_var: sshFiles
  become: true

- name: pull Home Assistant repo
  git:
    dest: "{{ appData }}/homeAssistant"
    repo: https://github.com/tom-erik-l/homeAssistant.git
  become: true


