- name: docker swarm leave
  docker_swarm:
    state: absent
    force: yes
  become: true

- name: plex container
  docker_container:
    name: plex
    image: linuxserver/plex
    env:
      PUID: "${PUID}"
      PGID: "${PGID}"
      VERSION: "docker"
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage/TV Shows:/tv
      - /mnt/storage/Movies:/movies
      - /mnt/storage/Music:/Music
    network_mode: host
    pull: yes
    restart: yes
    state: started
    restart_policy: unless-stopped 
    healthcheck:
      test: curl ${CURL_OPTS} "http://${TARGET}:32400/identity" >/dev/null  
  become: true

- name: allow plex in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "32400"
  become: true
