- name: plex container
  docker_container:
    name: plex
    image: linuxserver/plex
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      VERSION: "docker"
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage/TV Shows:/tv
      - /mnt/storage/Movies:/movies
      - /mnt/storage/Music:/Music
    network_mode: host
    pull: yes
    restart: yes
    state: started
    restart_policy: unless-stopped 
    # Doesn't work for some reason
    # healthcheck:
      # test: "CMD curl ${CURL_OPTS} 'http://localhost:32400/identity' >/dev/null"
  become: true

- name: allow plex in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "32400"
  become: true

- name: portainer container
  docker_container: 
    name: portainer
    image: portainer/portainer
    volumes:
    - /opt/appdata/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    pull: yes
    restart: yes
    state: started
    restart_policy: always
  become: true

- name: allow portainer in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "9000"
  become: true