- name: pihole container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    env: 
      TZ: "{{ timeZone }}"
      ServerIP: "{{ ansible_default_ipv4.address }}"

      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - '/opt/appdata/pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    network_mode: host
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped 
