- name: plex container
  docker_container:
    name: plex
    image: linuxserver/plex
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      VERSION: "docker"
    volumes:
      - "{{ appData }}/plex:/config"
      - "{{ storageData }}/TV Shows:/{{ storageData }}/TV Shows"
      - "{{ storageData }}/Movies:{{ storageData }}/Movies/movies"
      - "{{ storageData }}/Music:{{ storageData }}/Music"
    network_mode: host
    pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped
    # Doesn't work for some reason
    # healthcheck:
      # test: "CMD curl ${CURL_OPTS} 'http://localhost:32400/identity' >/dev/null"
  become: true

- name: allow plex in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "32400"
  become: true