- name: sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:preview
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timeZone }}"
      UMASK_SET: "022" #optional
    volumes:
      - "{{ appData }}/sonarr:/config"
      - "{{ storageData }}:{{ storageData }}"
      - "{{ storageData }}/empty:/tv"
    network_mode: host
    pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped
  become: true

- name: allow sonarr in UFW firewall
  ufw:
    rule: allow
    proto: tcp
    port: "8989"
  become: true