- include_vars: vault.yml

- name: transmission container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timeZone }}"
      TRANSMISSION_WEB_HOME: "/transmission-web-control/"
      USER: "{{ transmissionWebUIUser }}"
      PASS: "{{ transmissionWebUIPassword }}"
    volumes:
      - "{{ appData }}/transmission:/config"
      - "{{ storageData }}:{{ storageData }}"
      - "{{ storageData }}/empty:/downloads"
      - /home/tom-erik/sambashare/transmissionWatch:/watch
    network_mode: host
    # pull: yes
    restart: "{{ restart_containers }}"
    state: started
    restart_policy: unless-stopped
  become: true

- name: clean up transmission docker dirs
  file:
    path: "{{ file_item }}"
    state: absent
  with_items:
  - /mnt/storage/complete
  - /mnt/storage/incomplete
  loop_control:
    loop_var: file_item
  become: true

- name: allow transmission in UFW firewall
  ufw:
    rule: allow
    proto: "{{ UFW_item.proto }}"
    port: "{{ UFW_item.port }}"
  with_items:
    - {port: 9091, proto: tcp}
    - {port: 51413, proto: tcp}
    - {port: 51413, proto: udp}
  loop_control:
    loop_var: UFW_item
  become: true
