# based on:
# https://github.com/IronicBadger/ansible/tree/master/roles/docker
# https://docs.docker.com/engine/install/ubuntu

- name: install packages required by docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
    state: present
    update_cache: yes
  become: true  

- name: add docker repository key
  apt_key:
    id: "{{ apt_key.key }}"
    url: "{{ apt_key.url }}"
    state: present
  become: true
#   register: add_repository_key
#   ignore_errors: true

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_key.repository }}"
    update_cache: yes
    state: present
  become: true

- name: install (or update) docker 
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true  
#   notify:
#     - systemd daemon-reload
#     - restart docker service

# - name: start docker
#   service:
#     name: docker
#     state: started