# based on:
# https://github.com/IronicBadger/ansible/tree/master/roles/docker
# https://docs.docker.com/engine/install/ubuntu

- name: install packages required by docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
      - python-pip
    state: present
    update_cache: yes
  become: true  

- name: add docker repository key
  apt_key:
    id: "{{ apt_key.sig }}"
    url: "{{ apt_key.url }}"
    state: present
  become: true
#   register: add_repository_key

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_key.repository }}"
    update_cache: yes
    state: present
  become: true

- name: install (or update) docker 
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes   
  become: true  
  notify:
    - systemd daemon-reload
    - restart docker service
    - start docker service

- name: install docker python tools
  pip: 
    name:
    - docker
    - jsondiff
    - pyyaml
  become: true
  notify:
  - systemd daemon-reload
  - restart docker service
  - start docker service

- name: create group for docker appdata
  group:
    name: "{{dockergroup}}"
    state: present
    gid: "{{PGID}}"
  become: true

- name: create user for docker appdata
  user:
    name: "{{dockeruser}}"
    shell: /sbin/nologin
    uid: "{{PUID}}"
    group: "{{dockergroup}}"
  become: true

- name: create docker appdata base directory
  file:
    dest: "{{ appdata }}/{{item}}"
    state: directory
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
  with_items:
    - plex
    - portainer
    - transmission
  become: true

- name: set docker PUID and PGID environment variables for docker stack
  blockinfile:
    path: /etc/environment
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: ""
  become: true  
