#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml
- hosts: cartmanAnsibleAdmin
  vars:
    restart_containers: false
    containers: # Docker containers
    - plex
    - portainer
    - transmission
    - pihole
    - tautulli
    - sonarr
    - radarr
    # - organizr
    - bazarr
    - homeAssistant
    - lidarr
    appData: /opt/appdata
    storageData: /mnt/storage
    PUID: "1050" # User and group for docker
    PGID: "1050"
    timeZone: "Europe/Copenhagen"

  tasks:
  - name: test connection with -m ping
    ping:

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - name: Install applications
    apt:
      pkg:
        - smartmontools
        - curl
        - python
        - git
      state: present
    become: true


  # - name: populate service facts
  #   service_facts:
  # - debug:
  #     var: ansible_facts.services

  roles:
  - {role: mergerfs, tags: mergerfs}
  - {role: samba, tags: samba}
  - {role: docker, tags: docker}
  - {role: docker_container, tags: docker_container}