#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml
- hosts: cartmanAnsibleAdmin
  vars:
    restart_containers: true
    containers: # Docker containers
    - plex
    - portainer
    - transmission
    #- pihole
    - tautulli
    - sonarr
    - radarr
    # - organizr
    # - bazarr
    - homeAssistant
    # - lidarr
    #- tdarr
    - zigbee2mqtt
    appData: /opt/appdata
    storageData: /mnt/storage
    PUID: "1050" # User and group for docker
    PGID: "1050"
    timeZone: "Europe/Copenhagen"

  tasks:
  - name: test connection with -m ping
    ping:

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - name: Install applications
    apt:
      pkg:
        - smartmontools
        - curl
        - python
        - git
        - nethogs     # View network transfer rates
        - tree
        - htop
        - bridge-utils # To configure network bridge
        - unrar
      state: present
    become: true

  - name: populate service facts
    service_facts:
  - debug:
      var: ansible_facts.services

# Back up of :
#  /etc/netplan/01-netcfg.yaml
#
# # This file describes the network interfaces available on your system
# # For more information, see netplan(5).
# network:
#   version: 2
#   renderer: networkd
#   ethernets:
#     eno1:
#       dhcp4: yes
#       nameservers:
#         addresses: [1.1.1.1,1.0.0.1]

  - name: configure 4 port NIC as bridge to internal NIC
    blockinfile:
      path: /etc/netplan/01-netcfg.yaml # Name of the default netplan config file for Ubuntu server
      backup: yes
      marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
      insertafter: "eno1:"
      block: |2
              dhcp4: no
            enp3s0f0:
              dhcp4: no
            enp3s0f1:
              dhcp4: no
            enp4s0f0:
              dhcp4: no
            enp4s0f1:
              dhcp4: no
          bridges:
            br0:
              interfaces: [eno1, enp3s0f0, enp3s0f1, enp4s0f0, enp4s0f1]
      # validate: 'sudo netplan try -config-file %s'
    tags:
      - netplan
    become: true


  roles:
  - {role: mergerfs, tags: mergerfs}
  - {role: samba, tags: samba}
  - {role: docker, tags: docker}
  - {role: docker_container, tags: docker_container}
  - {role: ansible-rclone, tags: rclone}
  - {role: snapraid, tags: snapraid}