#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml 
- hosts: cartman 
  #remote_user: tom-erikAnsibleAdmin

  tasks:
  - name: test connection with -m ping
    ping: 

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - name: Install applications
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items: 
      - smartmontools
    become: true


      
     
  # - include_role:
  #     name: mergerfs
