#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml 
- hosts: cartmanAnsibleAdmin 

  tasks:
  - name: test connection with -m ping
    ping: 

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - name: Install applications
    apt:
      pkg:
        - smartmontools
      state: present
    become: true    
     
  - include_role:
      name: mergerfs

  # - name: populate service facts
  #   service_facts:
  # - debug:
  #     var: ansible_facts.services

  - include_role: 
      name: samba

  - include_role: 
      name: docker

