#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml 
- hosts: cartmanAnsibleAdmin 

  tasks:
  - name: test connection with -m ping
    ping: 

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - name: Install applications
    apt:
      pkg:
        - smartmontools
        - curl
        - python
        - git
      state: present
    become: true    

  # - name: populate service facts
  #   service_facts:
  # - debug:
  #     var: ansible_facts.services

  vars:
    restart_containers: true

  roles:
    - {role: mergerfs, tags: mergerfs}
    - {role: samba, tags: samba}
    - {role: docker, tags: docker}
    - {role: docker_container, tags: docker_container}