#Run the playbook by:
#ansible-playbook initialServerSetupPlaybook.yml -i hosts.yaml  -K 
#do not add: -u tom-erik 
#Will cause error according to: https://stackoverflow.com/questions/40983674/ansible-non-root-sudo-user-and-become-privilege-escalation

- hosts: cartman

  tasks:
  - name: test connection with -m ping
    ping: 

  - name: who am I?
    command: whoami
    register: out
  - debug: var=out.stdout_lines

  - include_role:
      name: ansibleAndServerSetup
