################################################################################
# samba
################################################################################
- name: install samba
  apt:
    pkg: samba
    state: present
  notify:
    - start samba service

- name: install samba config
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: |
      [storage]
        comment = storage@cartman
        path = /mnt/storage
        read only = no
        browsable = yes
        create mask = 0644
        directory mask = 0755
        # hide unreadable = yes #
        hide files = /lost+found/ #Alternatively use "hide files" (but is shown with hidden files shown in Windows)

      [homeAssisstant]
        comment = homeAssisstant@cartman
        path = /opt/appdata/homeAssistant
        read only = no
        browsable = yes
        create mask = 0644
        directory mask = 0755
        # hide unreadable = yes #
        hide files = /lost+found/ #Alternatively use "hide files" (but is shown with hidden files shown in Windows)
    validate: 'testparm -s %s'
  become: true
  notify:
    - restart nmbd
    - restart samba-ad-dc
    - restart smbd

- name: remove map to bad user
  lineinfile:
    path: /etc/samba/smb.conf
    regexp: "^$map to guest*"
    line: ';\1'
    backrefs: yes
  become: true

- name: allow samba in UFW firewall
  ufw:
    rule: allow
    name: Samba
  become: true
